#!/usr/bin/env python
#
# Copyright (c) 2014 Marin Atanasov Nikolov <dnaeon@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer
#    in this position and unchanged.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR(S) ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

"""
infoblox-cli is the Infoblox CLI client application.

It is used for getting, creating, updating and
removing of objects from an Infoblox server instance.

"""

from docopt import docopt
from infoblox.core import Infoblox

def main():
    
    usage="""
Usage:
  infoblox-cli -f <config> -t <objtype> get
  infoblox-cli -f <config> -t <objtype> -d <data> create
  infoblox-cli -f <config> -r <objref> -d <data> update
  infoblox-cli -f <config> -r <objref> remove
  infoblox-cli --help
  infoblox-cli --version

Arguments:
  get                             Get Infoblox objects
  create                          Create an Infoblox object
  update                          Update an Infoblox object
  remove                          Delete an Infoblox object

Options:
  -h, --help                      Display this usage info
  -v, --version                   Display version and exit
  -f <config>, --file <config>    Use the specified config file
  -t <objtype>, --type <objtype>  Specify the Infoblox object type,
                                  e.g. 'network', 'range', etc.
  -d <data>, --data <data>        Payload with data to send
  -r <objref>, --ref <objref>     Infoblox object reference

"""

    args = docopt(usage, version='0.1.0')

    import os.path
    if os.path.isfile(args['--file']):
      ib = Infoblox(args['--file'])
    else:
      print "Error importing conf file"

    if args['get']:
        result = ib.get_object(args['--type'], args['--data'])
    elif args['create']:
        result = ib.create_object(args['--type'], args['--data'])
    elif args['update']:
        result = ib.update_object(args['--ref'], args['--data'])
    elif args['remove']:
        result = ib.remove_object(args['--ref'])

    print result
        
if __name__ == '__main__':
    main()


